// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxy60g-Zo4-O-LqNY3LknfCdJmYCdcPZY',
    appId: '1:663948628846:web:fa14f4eb8178befd3e277f',
    messagingSenderId: '663948628846',
    projectId: 'shopping-18978',
    authDomain: 'shopping-18978.firebaseapp.com',
    storageBucket: 'shopping-18978.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcFgaOKQA-haMNd6RhK3RbUna5pAygL_Y',
    appId: '1:663948628846:android:6548719f9789adc23e277f',
    messagingSenderId: '663948628846',
    projectId: 'shopping-18978',
    storageBucket: 'shopping-18978.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjH-OzTzcS-nd2fKb1AgVDgVGEouEPPSA',
    appId: '1:663948628846:ios:ac931bf19191d29d3e277f',
    messagingSenderId: '663948628846',
    projectId: 'shopping-18978',
    storageBucket: 'shopping-18978.appspot.com',
    iosBundleId: 'com.example.shoppinggetx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjH-OzTzcS-nd2fKb1AgVDgVGEouEPPSA',
    appId: '1:663948628846:ios:cb987b3ec550aa143e277f',
    messagingSenderId: '663948628846',
    projectId: 'shopping-18978',
    storageBucket: 'shopping-18978.appspot.com',
    iosBundleId: 'com.example.shoppinggetx.RunnerTests',
  );
}
