// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9tiQgJZItCR-L6R7fJToOxl-N_Xf_vOA',
    appId: '1:666347984736:web:eec1e10b0081d7aae13005',
    messagingSenderId: '666347984736',
    projectId: 'myphim-3daf3',
    authDomain: 'myphim-3daf3.firebaseapp.com',
    storageBucket: 'myphim-3daf3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4Q66Min86ZLOqpYOyK4e_I7V7FAfkT9Y',
    appId: '1:666347984736:android:87fbea326dc448f9e13005',
    messagingSenderId: '666347984736',
    projectId: 'myphim-3daf3',
    storageBucket: 'myphim-3daf3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6_NjMphWHjtmK7Le6Lb-B7aRjDKsxDqs',
    appId: '1:666347984736:ios:c6b2ef4db06aa925e13005',
    messagingSenderId: '666347984736',
    projectId: 'myphim-3daf3',
    storageBucket: 'myphim-3daf3.appspot.com',
    iosBundleId: 'com.example.moviegetx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6_NjMphWHjtmK7Le6Lb-B7aRjDKsxDqs',
    appId: '1:666347984736:ios:1867159a3e51e3c3e13005',
    messagingSenderId: '666347984736',
    projectId: 'myphim-3daf3',
    storageBucket: 'myphim-3daf3.appspot.com',
    iosBundleId: 'com.example.moviegetx.RunnerTests',
  );
}
